// Screen-driven cargo, service and observation fields; no automatic tax rules.
let cteExtraBuffer={};
const extraLists={
  cargoQuantities:{tab:'info',title:'Quantidades da carga',fields:[['quantity','Quantidade','number'],['unit','Unidade de medida'],['measureType','Tipo da medida'],['alternate','Exibir outra descrição para a unidade de medida?','checkbox'],['description','Outra descrição da unidade']]},
  taxpayerNotes:{tab:'notes',title:'Observações do contribuinte',fields:[['identifier','Identificador'],['description','Descrição']]},
  fiscalNotes:{tab:'notes',title:'Observações do fisco',fields:[['identifier','Identificador'],['description','Descrição']]}
};
function extraEntry(key){const spec=extraLists[key],buffer=cteExtraBuffer[key]||{};return `<div data-extra-list="${key}"><h3>${spec.title}</h3><div id="extra-table-${key}">${extraTable(key)}</div><div class="cte-grid collection-entry">${spec.fields.map(([field,label,type='text'])=>type==='checkbox'?`<label class="check-field"><input type="checkbox" data-extra-key="${key}" data-extra-field="${field}" ${buffer[field]?'checked':''}>${label}</label>`:`<label>${label}<input data-extra-key="${key}" data-extra-field="${field}" type="${type}" ${type==='number'?'min="0" step="any"':'maxlength="500"'} value="${esc(buffer[field]||'')}" ${field==='description'&&key==='cargoQuantities'&&!buffer.alternate?'disabled':''}></label>`).join('')}</div><p class="extra-error" id="extra-error-${key}" role="alert"></p><button type="button" class="button secondary" data-extra-add="${key}">Adicionar ${key==='cargoQuantities'?'quantidade':'observação'}</button></div>`;}
function extraTable(key){const quantity=key==='cargoQuantities';return cteTable(quantity?['Quantidade','Unidade de medida','Tipo da medida','Outra descrição','Ação']:['Identificador','Descrição','Ação'],(draft[key]||[]).map((item,i)=>`<tr>${(quantity?[item.quantity,item.unit,item.measureType,item.alternate?item.description:'—']:[item.identifier,item.description]).map(value=>`<td class="wrap-cell">${esc(value||'—')}</td>`).join('')}<td><button type="button" class="row-action danger" data-extra-remove="${key}" data-index="${i}">Remover ${quantity?'quantidade':'observação'}</button></td></tr>`));}
function cteCargoPanel(){return `<div class="cte-subnav" role="tablist" aria-label="Informações da carga"><button type="button" role="tab" aria-selected="true" id="cargo-tab" aria-controls="cargo-panel">Carga</button>${['Seguro','Documentos anteriores','Produtos perigosos'].map(label=>`<button type="button" disabled title="Disponível em uma próxima etapa">${label} · em breve</button>`).join('')}</div><div id="cargo-panel" role="tabpanel" aria-labelledby="cargo-tab">${cteGrid(cteInfo)}<div class="cte-subform">${extraEntry('cargoQuantities')}</div></div>`;}
function cteTaxPanel(){return `<p class="section-help">Valores digitados manualmente. A opção de ICMS e o percentual são apenas registrados; não alteram os valores nem calculam tributos.</p>${cteGrid(cteServices)}<div class="notice"><div><strong>Frete + outros valores: <span id="cte-total">${money(Number(draft.freight||0)+Number(draft.otherCharges||0))}</span></strong><p>Soma demonstrativa independente do valor da prestação e do valor a receber.</p></div></div><h3>Impostos</h3>${['ICMS','IBS UF','IBS Municipal','CBS'].map(name=>`<details class="tax-group"><summary>${name}</summary><p>Configuração ainda não disponível neste protótipo. Nenhum imposto é calculado ou validado.</p></details>`).join('')}`;}
function cteNotesPanel(){return cteGrid([['operationNotes','Observação geral','textarea']])+`<div class="cte-subnav" role="tablist" aria-label="Tipos de observação"><button type="button" role="tab" id="obs-taxpayer-tab" aria-controls="obs-taxpayer-panel" aria-selected="true" data-obs-tab="taxpayer">Obs. Contribuinte</button><button type="button" role="tab" id="obs-fiscal-tab" aria-controls="obs-fiscal-panel" aria-selected="false" tabindex="-1" data-obs-tab="fiscal">Obs. Fisco</button></div><section role="tabpanel" id="obs-taxpayer-panel" aria-labelledby="obs-taxpayer-tab">${extraEntry('taxpayerNotes')}</section><section role="tabpanel" id="obs-fiscal-panel" aria-labelledby="obs-fiscal-tab" hidden>${extraEntry('fiscalNotes')}</section>`;}
const cteBaseCollect=cteCollect;
cteCollect=function(){cteBaseCollect();document.querySelectorAll('[data-extra-key]').forEach(input=>{(cteExtraBuffer[input.dataset.extraKey]??={})[input.dataset.extraField]=input.type==='checkbox'?input.checked:input.value.trim()});};
function selectObservation(id){document.querySelectorAll('[data-obs-tab]').forEach(b=>{const active=b.dataset.obsTab===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});$('#obs-taxpayer-panel').hidden=id!=='taxpayer';$('#obs-fiscal-panel').hidden=id!=='fiscal';}
function extraPending(){cteCollect();for(const [key,buffer] of Object.entries(cteExtraBuffer)){if(Object.values(buffer).some(v=>v!==''&&v!==false)){cteSelect(extraLists[key].tab);if(key!=='cargoQuantities')selectObservation(key==='taxpayerNotes'?'taxpayer':'fiscal');$('#cte-error').textContent=`Adicione o registro de “${extraLists[key].title}” à lista ou limpe os campos antes de salvar ou revisar.`;return true}}return false;}
function cteWireExtras(){
  document.querySelectorAll('[data-obs-tab]').forEach(b=>{b.onclick=()=>selectObservation(b.dataset.obsTab);b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const id=e.key==='Home'?'taxpayer':e.key==='End'?'fiscal':b.dataset.obsTab==='taxpayer'?'fiscal':'taxpayer';selectObservation(id);document.querySelector(`[data-obs-tab="${id}"]`).focus()}}});
  const toggle=$('[data-extra-key="cargoQuantities"][data-extra-field="alternate"]');toggle.onchange=()=>{const description=$('[data-extra-key="cargoQuantities"][data-extra-field="description"]');description.disabled=!toggle.checked;if(!toggle.checked)description.value='';};
  document.querySelectorAll('[data-extra-add]').forEach(button=>button.onclick=()=>{cteCollect();const key=button.dataset.extraAdd,entry={...cteExtraBuffer[key]};const fields=Array.from(document.querySelectorAll(`[data-extra-key="${key}"]`));const invalid=fields.find(x=>!x.validity.valid);if(invalid){invalid.reportValidity();return}const error=$(`#extra-error-${key}`);if(key==='cargoQuantities'?(entry.quantity===''||!entry.unit||!entry.measureType||(entry.alternate&&!entry.description)):(!entry.identifier||!entry.description)){error.textContent=key==='cargoQuantities'?'Informe quantidade, unidade e tipo da medida. Se habilitada, preencha a outra descrição.':'Informe identificador e descrição.';return}(draft[key]??=[]).push(entry);cteExtraBuffer[key]={};fields.forEach(x=>{if(x.type==='checkbox')x.checked=false;else x.value=''});if(key==='cargoQuantities')toggle.onchange();error.textContent='';$(`#extra-table-${key}`).innerHTML=extraTable(key);wireExtraRemove(key);});
  Object.keys(extraLists).forEach(wireExtraRemove);
  $('#cte-form').addEventListener('click',e=>{if(e.target.closest('#cte-save,#cte-finish,button[type="submit"]')&&extraPending()){e.preventDefault();e.stopImmediatePropagation()}},true);
}
function wireExtraRemove(key){document.querySelectorAll(`[data-extra-remove="${key}"]`).forEach(button=>button.onclick=()=>{draft[key].splice(Number(button.dataset.index),1);$(`#extra-table-${key}`).innerHTML=extraTable(key);wireExtraRemove(key)});}
const cteBaseReview=cteReview;
cteReview=function(){cteBaseReview();$('#cte-finish').insertAdjacentHTML('beforebegin',`<div class="review-box"><h3>Carga e observações</h3>${Object.entries(extraLists).map(([key,spec])=>`<h4>${spec.title}</h4>${extraTable(key)}`).join('')}</div>`);document.querySelectorAll('#cte-review [data-extra-remove]').forEach(button=>button.remove());};
