// CT-e form based on the supplied screen references; all records are demonstration drafts.
const cteTabs=[['details','Detalhes'],['documents','Documentos'],['sender','Remetente'],['recipient','Destinatário'],['others','Outros'],['modal','Modal'],['info','Informações'],['services','Serviços e Impostos'],['notes','Observações'],['review','Revisão']];
let cteActive='details',cteDocumentEdit=null,cteDocBuffer={docType:'NFe (Nota Fiscal Eletrônica)'};
const choices=values=>values.map(value=>[value,value]);
const cteDetails=[['company','Transportadora','select',()=>db.company.map(c=>[c.id,c.name])],['number','Número (referência manual)'],['series','Série do CT-e'],['payment','Pagamento','select',()=>choices(['Não informado','Pago','A pagar'])],['service','Serviço','text'],['mode','Tipo modal','select',()=>choices(['Rodoviário'])],['cteType','Tipo de CT-e'],['printLayout','Impressão','select',()=>choices(['Retrato','Paisagem'])],['payer','Tomador','select',()=>choices(['Remetente','Destinatário','Outro'])],['cfop','CFOP (informado manualmente)'],['issuedAt','Data de emissão informada','datetime-local'],['payerIeIndicator','Indicador IE do tomador'],['globalized','Globalizado','select',()=>choices(['Não informado','Não','Sim'])],['receiverPickup','Recebedor retira no aeroporto, filial, porto ou estação de destino?','checkbox'],['pickupDetails','Detalhes da retirada do recebedor','textarea'],['issueCity','Localidade de emissão'],['originCity','Início da prestação — município'],['originState','UF de início','select',()=>ufOptions],['destinationCity','Término da prestação — município'],['destinationState','UF de término','select',()=>ufOptions]];
function participantFields(prefix){return [[prefix+'Foreign','O participante é do exterior?','checkbox'],[prefix+'Document','CPF / CNPJ'],[prefix+'Ie','Inscrição estadual'],[prefix,'Razão social'],[prefix+'TradeName','Nome fantasia'],[prefix+'Phone','Telefone principal','tel'],[prefix+'Phone2','Telefone secundário','tel'],[prefix+'Activity','Atividade'],[prefix+'PostalCode','CEP'],[prefix+'Street','Endereço principal'],[prefix+'Number','Número'],[prefix+'District','Bairro'],[prefix+'Complement','Complemento'],[prefix+'City','Cidade'],[prefix+'State','UF','select',()=>ufOptions],[prefix+'Email','E-mail geral','email'],[prefix+'EmailXml','Enviar XML para e-mail geral (simulação)','checkbox'],[prefix+'ContactEmail','E-mail do contato','email'],[prefix+'ContactXml','Enviar XML para contato (simulação)','checkbox'],[prefix+'AccountantEmail','E-mail do contador','email'],[prefix+'AccountantXml','Enviar XML para contador (simulação)','checkbox']];}
const cteInfo=[['cargoValue','Valor total da carga (R$)','number'],['product','Produto predominante'],['insuredCargoValue','Valor da carga para averbação (R$)','number'],['container','Container'],['containerDelivery','Entrega do container','date'],['containerSeal','Número do lacre do container'],['cargoCharacteristics','Outras características'],['transportCharacteristics','Característica do transporte'],['serviceCharacteristics','Característica do serviço'],['weight','Peso informado anteriormente (kg)','number'],['invoiceReference','Referência da nota fiscal da versão anterior']];
const cteServices=[['freight','Valor do frete (R$)','number'],['serviceValue','Valor da prestação (R$)','number'],['receivableValue','Valor a receber (R$)','number'],['includeIcms','Incluir ICMS no frete? (simulação)','checkbox'],['includePercentage','Percentual a incluir (%)','number'],['otherCharges','Outros valores (R$)','number'],['taxClassification','Código de classificação tributária'],['donation','Doação','checkbox']];
const docFields=[['docType','Tipo de documento','select',()=>choices(['NFe (Nota Fiscal Eletrônica)'])],['docNumber','Número'],['docKey','Chave (fictícia)'],['docDate','Data de emissão','date'],['docCfop','CFOP'],['docWeight','Peso (kg)','number'],['docValue','Valor da nota fiscal (R$)','number'],['docEdi','Número de referência EDI'],['docControl','Número de controle do cliente'],['docPin','PIN SUFRAMA'],['docNcm','NCM predominante']];
const cteModal=[['rntrc','RNTRC'],['deliveryForecast','Previsão de entrega','date'],['ciot','CIOT'],['fullLoad','Indicador de lotação','checkbox']];
const cteAllFields=[...cteDetails,...participantFields('sender'),...participantFields('recipient'),['payerName','Nome do outro tomador'],...cteInfo,...cteServices,...cteModal,['operationNotes','Observação geral','textarea']];
function cteInput([key,label,type='text',options],source=draft){
  const value=source[key]??'';const wide=type==='textarea'||['company','sender','recipient'].includes(key);
  if(type==='checkbox')return `<label class="check-field"><input data-cte-field type="checkbox" name="${key}" ${value===true?'checked':''}>${label}</label>`;
  let control;if(type==='select'){const items=options();if(value&&!items.some(([id])=>id===value))items.push([value,`${value} (valor anterior)`]);control=`<select data-cte-field name="${key}"><option value="">Selecione</option>${items.map(([id,text])=>`<option value="${esc(id)}" ${value===id?'selected':''}>${esc(text)}</option>`).join('')}</select>`}
  else if(type==='textarea')control=`<textarea data-cte-field name="${key}" maxlength="4000" rows="3">${esc(value)}</textarea>`;
  else control=`<input data-cte-field name="${key}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01" max="999999999"':'maxlength="200"'}>`;
  return `<label class="${wide?'wide-field':''}">${label}${control}</label>`;
}
function cteGrid(fields,source=draft){return `<div class="cte-grid">${fields.map(f=>cteInput(f,source)).join('')}</div>`;}
function cteCollect(){document.querySelectorAll('#cte-form [data-cte-field]').forEach(input=>{if(input.name.startsWith('doc'))cteDocBuffer[input.name]=input.value.trim();else draft[input.name]=input.type==='checkbox'?input.checked:input.value.trim()});}
function cteTable(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">Nenhum registro incluído.</td></tr>`}</tbody></table></div>`;}
function cteDocs(){return `<p class="section-help">Inclua um ou mais documentos fictícios. Nenhuma chave ou nota será consultada ou validada.</p><div id="cte-doc-table">${cteTable(['Número','Data de emissão','Chave','Valor total','Opções'],draft.documents.map((d,i)=>`<tr><td>${esc(d.docNumber||'—')}</td><td>${esc(d.docDate||'—')}</td><td class="key-cell">${esc(d.docKey||'—')}</td><td>${money(d.docValue)}</td><td><button type="button" class="row-action" data-doc-edit="${i}">Editar documento</button><button type="button" class="row-action danger" data-doc-remove="${i}">Remover documento</button></td></tr>`))}</div><div class="cte-subform" id="doc-entry"><h3>${cteDocumentEdit===null?'Incluir documento':'Editar documento'}</h3>${cteGrid(docFields,cteDocBuffer)}<p id="doc-error" role="alert"></p><button type="button" class="button secondary" id="doc-save">${cteDocumentEdit===null?'Adicionar documento':'Atualizar documento'}</button>${cteDocumentEdit!==null?'<button type="button" class="button secondary" id="doc-cancel">Cancelar edição</button>':''}</div>`;}
function cteFleet(){return cteGrid(cteModal)+`<div class="cte-subform"><h3>Veículos vinculados</h3>${cteTable(['Placa','UF','RENAVAM','Propriedade','Tipo','Carroceria','Ação'],draft.cteVehicles.map((v,i)=>`<tr>${[v.plate,v.state,v.renavam,v.ownership,v.type,v.body].map(x=>`<td>${esc(x||'Não informado')}</td>`).join('')}<td><button type="button" class="row-action danger" data-vehicle-remove="${i}">Remover veículo</button></td></tr>`))}<div class="cte-grid collection-entry"><label>Veículo cadastrado<select id="cte-vehicle-pick"><option value="">Selecione</option>${db.vehicles.map(v=>`<option value="${esc(v.id)}">${esc(v.plate)} • ${esc(modelName(v.model))}</option>`).join('')}</select></label><label>UF do veículo<select id="cte-vehicle-state"><option value="">Não informada</option>${ufOptions.map(([id])=>`<option>${id}</option>`).join('')}</select></label><label>RENAVAM<input id="cte-vehicle-renavam" maxlength="30"></label><label>Propriedade<select id="cte-vehicle-ownership"><option value="">Não informada</option><option>Próprio</option><option>Terceiro</option></select></label><label>Tipo do veículo<input id="cte-vehicle-type" maxlength="60"></label><label>Carroceria<input id="cte-vehicle-body" maxlength="60"></label></div><p class="section-help">Informações complementares ficam neste rascunho, sem alterar o cadastro da frota.</p><button type="button" class="button secondary" id="cte-add-vehicle">Adicionar veículo</button></div><div class="cte-subform"><h3>Motoristas vinculados</h3>${cteTable(['Nome','CPF (fictício)','CNH','Ação'],draft.cteDrivers.map((d,i)=>`<tr><td>${esc(d.name)}</td><td>${esc(d.document||'—')}</td><td>${esc(d.license||'—')}</td><td><button type="button" class="row-action danger" data-driver-remove="${i}">Remover motorista</button></td></tr>`))}<div class="collection-entry"><label>Motorista cadastrado<select id="cte-driver-pick"><option value="">Selecione</option>${db.drivers.map(d=>`<option value="${esc(d.id)}">${esc(d.name)}</option>`).join('')}</select></label><button type="button" class="button secondary" id="cte-add-driver">Adicionar motorista</button></div></div>`;}
const originalEmissionEditor=emissionEditor;
emissionEditor=function(){if(route!=='cte')return originalEmissionEditor();cteActive='details';cteDocumentEdit=null;cteDocBuffer={docType:'NFe (Nota Fiscal Eletrônica)'};draft.cargoQuantities??=[];draft.taxpayerNotes??=[];draft.fiscalNotes??=[];cteExtraBuffer={};draft.documents??=[];draft.cteVehicles??=[];draft.cteDrivers??=[];draft.mode??='Rodoviário';cteRender();};
function cteRender(){
  const notice='<p class="section-help">Informações básicas disponíveis nesta etapa do protótipo.</p>';
  const bodies={details:`<p class="section-help">Preenchimento manual de demonstração. Número, série, CFOP e data não representam emissão ou validação fiscal.</p>${cteGrid(cteDetails)}`,documents:cteDocs(),sender:`<p class="section-help">Quem envia a carga. Preencha os dados de identificação, endereço e contatos separadamente. Consultas automáticas e envio de XML ainda não estão integrados.</p>${cteGrid(participantFields('sender'))}`,recipient:`<p class="section-help">Quem recebe a carga. Os dados são independentes dos dados do remetente.</p>${cteGrid(participantFields('recipient'))}`,others:`<p class="section-help">Preencha quando o tomador selecionado em Detalhes for “Outro”.</p>${cteGrid([['payerName','Nome do outro tomador']])}`,modal:`<h3>Rodoviário</h3>${cteFleet()}<p class="section-help">Outras informações de modal estarão disponíveis em uma próxima etapa.</p>`,info:cteCargoPanel(),services:cteTaxPanel(),notes:cteNotesPanel(),review:'<div id="cte-review"></div>'};
  $('#main').innerHTML=head(`CT-e • ${draft.reference}`,'Cadastro da operação organizado por assunto. Rascunho local, sem validade fiscal.')+`<div class="cte-context"><span><strong>Transportadora</strong> ${esc(pickCompany(draft.company))}</span><span><strong>Remetente</strong> ${esc(draft.sender||'Não informado')}</span><span><strong>Destinatário</strong> ${esc(draft.recipient||'Não informado')}</span></div><section class="panel cte-editor"><div class="cte-tabs" role="tablist" aria-label="Informações do CT-e">${cteTabs.map(([id,label])=>`<button type="button" id="cte-tab-${id}" role="tab" aria-controls="cte-panel-${id}" data-cte-tab="${id}">${label}</button>`).join('')}</div><form id="cte-form" novalidate>${cteTabs.map(([id,label])=>`<section class="cte-tab-panel" id="cte-panel-${id}" role="tabpanel" aria-labelledby="cte-tab-${id}" ${id!==cteActive?'hidden':''}><h2>${label}</h2>${bodies[id]}</section>`).join('')}<p id="cte-error" role="alert"></p><div class="cte-actions"><span class="badge amber">Simulação • sem autorização fiscal</span><button type="button" class="button secondary" id="cte-close">Fechar</button><button type="button" class="button secondary" id="cte-save">Salvar rascunho</button><button type="submit" class="button">Revisar preenchimento</button></div></form></section>`;
  document.querySelectorAll('[data-cte-tab]').forEach((button,index)=>{button.onclick=()=>{cteCollect();cteSelect(button.dataset.cteTab)};button.onkeydown=e=>{let next;if(e.key==='ArrowRight')next=(index+1)%cteTabs.length;if(e.key==='ArrowLeft')next=(index+cteTabs.length-1)%cteTabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=cteTabs.length-1;if(next!==undefined){e.preventDefault();cteCollect();cteSelect(cteTabs[next][0]);document.querySelector(`[data-cte-tab="${cteTabs[next][0]}"]`).focus()}}});
  $('#cte-save').onclick=()=>{cteCollect();if(ctePendingDocument()){cteSelect('documents');$('#cte-error').textContent='Adicione o documento à lista ou limpe os campos dele antes de salvar o rascunho.';return}persistDraft(false)};
  $('#cte-close').onclick=()=>{if(confirm('Fechar? Alterações não salvas serão descartadas.'))emissionList()};
  $('#cte-form').onsubmit=e=>{e.preventDefault();cteCollect();if(ctePendingDocument()){cteSelect('documents');$('#cte-error').textContent='Adicione o documento à lista antes de revisar.';return}const invalid=Array.from(e.currentTarget.elements).find(x=>x.willValidate&&!x.validity.valid);if(invalid){cteSelect(invalid.closest('[role=tabpanel]').id.replace('cte-panel-',''));$('#cte-error').textContent='Revise o formato do campo destacado.';invalid.focus();invalid.reportValidity();return}cteSelect('review')};
  $('#cte-form').oninput=()=>{$('#cte-total').textContent=money(Number($('#cte-form').elements.namedItem('freight').value||0)+Number($('#cte-form').elements.namedItem('otherCharges').value||0))};
  cteWireCollections();cteWireExtras();cteSelect(cteActive);
}
function ctePendingDocument(){return docFields.some(([key])=>key!=='docType'&&$('#cte-form').elements.namedItem(key).value.trim());}
function cteSelect(id){cteActive=id;document.querySelectorAll('[data-cte-tab]').forEach(b=>{b.setAttribute('aria-selected',String(b.dataset.cteTab===id));b.tabIndex=b.dataset.cteTab===id?0:-1});document.querySelectorAll('.cte-tab-panel').forEach(p=>p.hidden=p.id!==`cte-panel-${id}`);$('#cte-error').textContent='';if(id==='review')cteReview();}
function cteWireCollections(){
  $('#doc-save').onclick=()=>{cteCollect();const item={};for(const [key] of docFields){const field=$('#cte-form').elements.namedItem(key);if(!field.validity.valid){field.reportValidity();return}item[key]=field.value.trim()}if(!item.docKey||!item.docDate||item.docValue===''){$('#doc-error').textContent='Informe chave fictícia, data e valor para adicionar o documento de teste.';return}if(draft.documents.some((d,i)=>i!==cteDocumentEdit&&d.docKey===item.docKey)){$('#doc-error').textContent='Esta chave já foi incluída neste rascunho.';return}if(cteDocumentEdit===null)draft.documents.push(item);else draft.documents[cteDocumentEdit]=item;cteDocumentEdit=null;cteDocBuffer={docType:'NFe (Nota Fiscal Eletrônica)'};cteRender();};
  if($('#doc-cancel'))$('#doc-cancel').onclick=()=>{cteCollect();cteDocumentEdit=null;cteDocBuffer={docType:'NFe (Nota Fiscal Eletrônica)'};cteRender()};
  document.querySelectorAll('[data-doc-edit]').forEach(b=>b.onclick=()=>{cteCollect();cteDocumentEdit=Number(b.dataset.docEdit);cteDocBuffer={...draft.documents[cteDocumentEdit]};cteRender()});
  document.querySelectorAll('[data-doc-remove]').forEach(b=>b.onclick=()=>{cteCollect();draft.documents.splice(Number(b.dataset.docRemove),1);cteDocumentEdit=null;cteDocBuffer={docType:'NFe (Nota Fiscal Eletrônica)'};cteRender()});
  $('#cte-add-vehicle').onclick=()=>{cteCollect();const v=db.vehicles.find(v=>v.id===$('#cte-vehicle-pick').value);if(!v){toast('Selecione um veículo cadastrado.');return}if(draft.cteVehicles.some(x=>x.id===v.id)){toast('Este veículo já foi incluído.');return}draft.cteVehicles.push({id:v.id,plate:v.plate,state:$('#cte-vehicle-state').value,renavam:$('#cte-vehicle-renavam').value.trim(),ownership:$('#cte-vehicle-ownership').value,type:$('#cte-vehicle-type').value.trim(),body:$('#cte-vehicle-body').value.trim()});cteRender()};
  $('#cte-add-driver').onclick=()=>{cteCollect();const d=db.drivers.find(d=>d.id===$('#cte-driver-pick').value);if(!d){toast('Selecione um motorista cadastrado.');return}if(draft.cteDrivers.some(x=>x.id===d.id)){toast('Este motorista já foi incluído.');return}draft.cteDrivers.push({id:d.id,name:d.name,document:d.document,license:d.license});cteRender()};
  for(const [kind,key] of [['vehicle','cteVehicles'],['driver','cteDrivers']])document.querySelectorAll(`[data-${kind}-remove]`).forEach(b=>b.onclick=()=>{cteCollect();draft[key].splice(Number(b.dataset[kind+'Remove']),1);cteRender()});
}
function cteReview(){
  const missing=[['company','Transportadora','details'],['sender','Razão social do remetente','sender'],['recipient','Razão social do destinatário','recipient'],['payer','Tomador','details'],['originCity','Início da prestação','details'],['destinationCity','Término da prestação','details']].filter(([key])=>!draft[key]);if(draft.company&&!db.company.some(c=>c.id===draft.company))missing.push(['company','Transportadora cadastrada','details']);if(draft.payer==='Outro'&&!draft.payerName)missing.push(['payerName','Nome do outro tomador','others']);
  $('#cte-review').innerHTML=`<p class="section-help">Conferência de preenchimento do protótipo. Não representa validação tributária nem autorização de CT-e.</p>${missing.length?`<div class="notice"><div><strong>Complete a identificação para concluir a revisão</strong>${missing.map(([,label,tab])=>`<p><button type="button" class="row-action" data-fix-tab="${tab}">${label} →</button></p>`).join('')}</div></div>`:'<p class="badge">Identificação básica preenchida</p>'}<div class="review-box"><h3>Informações preenchidas</h3><dl class="cte-review-grid">${cteAllFields.filter(([key])=>draft[key]!==''&&draft[key]!=null).map(([key,label,type])=>`<div><dt>${esc(key.startsWith('sender')?'Remetente — '+label:key.startsWith('recipient')?'Destinatário — '+label:label)}</dt><dd>${esc(key==='company'?pickCompany(draft[key]):type==='checkbox'?(draft[key]?'Sim':'Não'):draft[key])}</dd></div>`).join('')}</dl></div><div class="review-box"><h3>Documentos e transporte</h3><p>${draft.documents.length} documento(s) • ${draft.cteVehicles.length} veículo(s) • ${draft.cteDrivers.length} motorista(s)</p><p>Valor das notas: ${money(draft.documents.reduce((sum,d)=>sum+Number(d.docValue||0),0))}</p><p>Frete + outros valores: ${money(Number(draft.freight||0)+Number(draft.otherCharges||0))}</p><p>Notas: ${esc(draft.documents.map(d=>d.docNumber||d.docKey).join(', ')||'Nenhuma')}</p><p>Veículos: ${esc(draft.cteVehicles.map(v=>v.plate).join(', ')||'Nenhum')}</p><p>Motoristas: ${esc(draft.cteDrivers.map(d=>d.name).join(', ')||'Nenhum')}</p></div><button type="button" class="button" id="cte-finish" ${missing.length?'disabled':''}>Concluir revisão do rascunho</button>`;
  document.querySelectorAll('[data-fix-tab]').forEach(b=>b.onclick=()=>cteSelect(b.dataset.fixTab));$('#cte-finish').onclick=()=>{const invalid=Array.from($('#cte-form').elements).find(x=>x.willValidate&&!x.validity.valid);if(invalid){cteSelect(invalid.closest('[role=tabpanel]').id.replace('cte-panel-',''));$('#cte-error').textContent='Revise o formato do campo destacado.';invalid.focus();invalid.reportValidity();return}persistDraft(true)};
}
