// Local workflow demonstration only: no tax calculation, XML or fiscal authorization.
for(const key of ['cteDrafts','mdfeDrafts'])if(!Array.isArray(db[key]))db[key]=[];
let draft=null,step=0;
const ufOptions='AC AL AP AM BA CE DF ES GO MA MT MS MG PA PB PR PE PI RJ RN RS RO RR SC SP SE TO'.split(' ').map(x=>[x,x]);
const money=n=>Number(n||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const emissionKey=()=>route==='cte'?'cteDrafts':'mdfeDrafts';
const emissionName=()=>route==='cte'?'CT-e':'MDF-e';
function emissionSteps(){return route==='cte'?['Empresa e participantes','Trajeto e carga','Valores e revisão']:['Empresa e percurso','Veículo e motorista','CT-e e revisão'];}
function pickCompany(id){return db.company.find(x=>x.id===id)?.name||'Empresa não cadastrada';}
function emissionField(key,label,type='text',options=[],required=false){
  const value=draft[key]??'';
  if(type==='select')return `<label>${label}${required?' *':''}<select name="${key}" ${required?'required':''}><option value="">Selecione</option>${options.map(([id,name])=>`<option value="${esc(id)}" ${value===id?'selected':''}>${esc(name)}</option>`).join('')}</select></label>`;
  return `<label>${label}${required?' *':''}<input name="${key}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='number'?'min="0" max="999999999" step="0.01"':'maxlength="200"'}></label>`;
}
function draftSummary(d){return route==='cte'?`${d.sender||'Remetente não informado'} → ${d.recipient||'Destinatário não informado'}`:`${d.originState||'UF inicial'} → ${d.destinationState||'UF final'}`;}
future=function(){draft=null;step=0;emissionList();};
function emissionList(){
  const rows=db[emissionKey()]||[];
  $('#main').innerHTML=head(`Preparar ${emissionName()}`,'Preencha e revise a operação antes de evoluirmos para a integração fiscal.',`<button class="button" id="new-draft">＋ Novo rascunho</button>`)+`<div class="notice emission-notice"><div><strong>Simulação • sem emissão fiscal</strong><p>Rascunhos locais para testar o processo. Não geram chave de acesso, XML, DACTE, DAMDFE ou autorização da SEFAZ.</p></div></div><section class="panel"><div class="panel-head"><h2>Rascunhos de ${emissionName()}</h2><span class="count">${rows.length} registro(s)</span></div>${rows.length?`<div class="table-wrap"><table><thead><tr><th>Referência interna</th><th>Empresa / operação</th><th>Situação</th><th>Ação</th></tr></thead><tbody>${rows.map(d=>`<tr><td><strong>${esc(d.reference)}</strong><small>Identificação do protótipo</small></td><td>${esc(pickCompany(d.company))}<small>${esc(draftSummary(d))}</small></td><td>${badge(d.status||'Rascunho')}</td><td><button class="row-action" data-draft="${esc(d.id)}">Abrir rascunho</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Nenhum rascunho ainda. Comece pelo botão “Novo rascunho”.</div>'}</section>`;
  $('#new-draft').onclick=()=>{draft={id:crypto.randomUUID(),reference:`DEMO-${route.toUpperCase()}-${String(rows.length+1).padStart(3,'0')}`,status:'Rascunho',company:db.company.length===1?db.company[0].id:'',linkedCtes:[]};step=0;emissionEditor()};
  document.querySelectorAll('[data-draft]').forEach(button=>button.onclick=()=>{draft=structuredClone(rows.find(d=>d.id===button.dataset.draft));step=0;emissionEditor()});
}
function collectDraft(){if(!$('#emission-form'))return;for(const [key,value] of new FormData($('#emission-form')))draft[key]=String(value).trim();if($('#cte-links'))draft.linkedCtes=Array.from(document.querySelectorAll('[data-link-cte]:checked')).map(x=>x.value);}
function emissionEditor(){
  const field=emissionField,companies=db.company.map(c=>[c.id,c.name]);let content='';
  if(step===0){content=field('company','Transportadora / empresa','select',companies,true);if(route==='cte')content+=field('sender','Remetente','text',[],true)+field('senderDocument','CPF / CNPJ do remetente (fictício)')+field('recipient','Destinatário','text',[],true)+field('recipientDocument','CPF / CNPJ do destinatário (fictício)')+field('payer','Tomador do serviço','select',[['Remetente','Remetente'],['Destinatário','Destinatário'],['Outro','Outro']],true)+field('payerName','Nome do tomador, quando “Outro”');else content+=field('originState','UF de carregamento','select',ufOptions,true)+field('loadingCity','Município de carregamento','text',[],true)+field('destinationState','UF de descarregamento','select',ufOptions,true)+field('unloadingCity','Município de descarregamento','text',[],true)+field('routeStates','UFs do percurso, em ordem (ex.: SC, PR, SP)')+field('departure','Data prevista de saída','date',[],true);}
  if(step===1&&route==='cte')content=field('originCity','Município de origem','text',[],true)+field('originState','UF de origem','select',ufOptions,true)+field('destinationCity','Município de destino','text',[],true)+field('destinationState','UF de destino','select',ufOptions,true)+field('product','Descrição da carga','text',[],true)+field('weight','Peso informado (kg)','number',[],true)+field('cargoValue','Valor informado da carga (R$)','number',[],true)+field('invoiceReference','Referência da nota fiscal (fictícia)');
  if(step===1&&route==='mdfe')content=field('vehicle','Veículo principal','select',db.vehicles.map(v=>[v.id,`${v.plate} • ${modelName(v.model)} • ${v.status}`]),true)+field('driver','Motorista','select',db.drivers.map(d=>[d.id,`${d.name} • ${d.status}`]),true)+`<div class="wide-field section-help">Este primeiro fluxo considera um veículo principal e um motorista. Reboques, múltiplos condutores e detalhes fiscais serão definidos nas próximas validações.</div>`;
  if(step===2&&route==='cte')content=field('freight','Valor do frete (R$)','number',[],true)+field('otherCharges','Outros valores (R$)','number')+field('operationNotes','Observações da operação')+`<div class="wide-field notice"><div><strong>Total informado: <span id="freight-total">${money(Number(draft.freight||0)+Number(draft.otherCharges||0))}</span></strong><p>Soma demonstrativa dos valores digitados, sem cálculo de impostos. Dados tributários e documentos fiscais não são validados.</p></div></div>`;
  if(step===2&&route==='mdfe'){const available=(db.cteDrafts||[]).filter(d=>d.company===draft.company);content=`<div class="wide-field"><h2>Rascunhos de CT-e da empresa</h2><p class="section-help">Selecione os rascunhos que representam a viagem. Eles não substituem CT-e autorizados.</p><div id="cte-links">${available.length?available.map(d=>`<label class="check-field"><input type="checkbox" data-link-cte value="${esc(d.id)}" ${(draft.linkedCtes||[]).includes(d.id)?'checked':''}>${esc(d.reference)} — ${esc(d.sender||'Remetente')} → ${esc(d.recipient||'Destinatário')} (${esc(d.status)})</label>`).join(''):'<p>Nenhum rascunho de CT-e desta empresa. Salve este MDF-e e prepare um CT-e para continuar a revisão.</p>'}</div></div>`+field('operationNotes','Observações da viagem');}
  $('#main').innerHTML=head(`${draft.reference} • ${emissionName()}`,'Rascunho demonstrativo. Campos com * permitem testar a revisão deste protótipo.')+`<ol class="emission-steps">${emissionSteps().map((label,index)=>`<li class="${step===index?'current':''}" ${step===index?'aria-current="step"':''}><span>${index+1}</span>${label}</li>`).join('')}</ol><section class="panel"><div class="panel-head"><h2>${emissionSteps()[step]}</h2><span class="badge amber">Sem validade fiscal</span></div><form id="emission-form" class="panel-body" novalidate><div class="form-grid">${content}</div>${step===2?`<div class="review-box"><h2>Resumo para conferência</h2><p>${esc(pickCompany(draft.company))}</p><p>${route==='cte'?`${esc(draft.sender||'—')} → ${esc(draft.recipient||'—')}<br>${esc(draft.originCity||'—')} / ${esc(draft.originState||'—')} → ${esc(draft.destinationCity||'—')} / ${esc(draft.destinationState||'—')}<br>Carga: ${esc(draft.product||'—')} • ${esc(draft.weight||'0')} kg`:`${esc(draft.loadingCity||'—')} / ${esc(draft.originState||'—')} → ${esc(draft.unloadingCity||'—')} / ${esc(draft.destinationState||'—')}<br>Veículo: ${esc(db.vehicles.find(v=>v.id===draft.vehicle)?.plate||'Não encontrado')} • Motorista: ${esc(driverName(draft.driver))}`}</p></div>`:''}<p id="emission-error" role="alert"></p><div class="wizard-actions"><button class="button secondary" type="button" id="draft-back">${step?'Voltar':'Fechar'}</button><button class="button secondary" type="button" id="draft-save">Salvar rascunho</button><button class="button" type="submit">${step===2?'Concluir revisão do rascunho':'Continuar'}</button></div></form></section>`;
  $('#draft-back').onclick=()=>{collectDraft();if(step){step--;emissionEditor()}else{if(confirm('Fechar este rascunho? Alterações não salvas serão descartadas.'))emissionList()}};
  $('#draft-save').onclick=()=>{collectDraft();persistDraft(false)};
  $('#emission-form').oninput=()=>{if($('#freight-total')){$('#freight-total').textContent=money(Number($('#emission-form').elements.namedItem('freight').value||0)+Number($('#emission-form').elements.namedItem('otherCharges').value||0))}};
  $('#emission-form').onsubmit=event=>{event.preventDefault();collectDraft();const invalid=Array.from(event.currentTarget.elements).find(e=>e.willValidate&&(!e.validity.valid||(e.required&&!e.value.trim())));if(invalid){$('#emission-error').textContent='Preencha os campos destacados para continuar.';invalid.focus();invalid.reportValidity();return}const issue=validateDraft(step);if(issue){$('#emission-error').textContent=issue;return}if(step<2){step++;emissionEditor()}else persistDraft(true)};
}
function validateDraft(through){
  if(!db.company.some(c=>c.id===draft.company))return 'Selecione uma empresa cadastrada.';
  if(route==='cte'){
    if(!draft.sender||!draft.recipient||!draft.payer)return 'Informe remetente, destinatário e tomador na primeira etapa.';
    if(draft.payer==='Outro'&&!draft.payerName)return 'Informe o nome do outro tomador do serviço.';
    if(through>=1&&['originCity','originState','destinationCity','destinationState','product','weight','cargoValue'].some(k=>!draft[k]))return 'Complete o trajeto e a carga na segunda etapa.';
    if(through===2&&(draft.freight==null||draft.freight===''))return 'Informe o valor do frete.';
  }else{
    if(['originState','loadingCity','destinationState','unloadingCity','departure'].some(k=>!draft[k]))return 'Complete o percurso e a data prevista na primeira etapa.';
    if(through>=1){const vehicle=db.vehicles.find(v=>v.id===draft.vehicle),driver=db.drivers.find(d=>d.id===draft.driver);if(!vehicle||!driver)return 'Selecione veículo e motorista cadastrados.';if(vehicle.status!=='Disponível'||driver.status!=='Ativo')return 'Para esta demonstração, escolha um veículo disponível e um motorista ativo.';}
    if(through===2&&(!(draft.linkedCtes||[]).length||draft.linkedCtes.some(id=>!(db.cteDrafts||[]).some(d=>d.id===id&&d.company===draft.company))))return 'Selecione ao menos um rascunho de CT-e da mesma empresa.';
  }
  return '';
}
function persistDraft(reviewed){
  draft.status=reviewed?'Rascunho revisado':'Rascunho';draft.updatedAt=new Date().toISOString();
  const key=emissionKey();if(!Array.isArray(db[key]))db[key]=[];const index=db[key].findIndex(d=>d.id===draft.id);if(index<0)db[key].push(structuredClone(draft));else db[key][index]=structuredClone(draft);
  const ok=save();emissionList();if(ok)toast(reviewed?'Revisão salva. Nenhum documento fiscal foi emitido.':'Rascunho salvo para continuar depois.');
}
const baseQueries=queries;
queries=function(){baseQueries();$('#main').insertAdjacentHTML('beforeend',`<section class="panel" style="margin-top:24px"><div class="panel-head"><h2>Rascunhos da operação</h2></div><div class="panel-body"><a class="quick" href="#cte">CT-e • ${(db.cteDrafts||[]).length} rascunho(s)<span>→</span></a><a class="quick" href="#mdfe">MDF-e • ${(db.mdfeDrafts||[]).length} rascunho(s)<span>→</span></a></div></section>`)};
render();
